Repository Gosrock/Gosrock-storybook, pull requests merged in 2022-01, with the labels that each got.

#17 컨테이너 스토리 추가
  package-lock.json
  src/index.js
  src/stories/Container/Container.css
  src/stories/Container/Container.jsx
  src/stories/Container/Container.stories.jsx
Labels: 기능 추가

#22 container layout grid
  src/stories/Container/Container.stories.jsx
  src/stories/Container/LayoutContainer/Container.css
  src/stories/Container/LayoutContainer/Container.jsx
  src/stories/Container/LayoutContainer/Container.stories.jsx
  src/stories/Container/Type1/TypeOne.css
  src/stories/Container/Type1/TypeOne.jsx
  src/stories/Container/Type2/TypeTwo.css
  src/stories/Container/Type2/TypeTwo.jsx
  src/stories/Container/Type3/TypeThree.css
  src/stories/Container/Type3/TypeThree.jsx
Labels: 기능 추가

#40 Wonjin
  src/index.js
  src/stories/Components/UtilityButton/KakaoTalk.svg
  src/stories/Components/UtilityButton/ShareAlt.svg
  src/stories/Components/UtilityButton/UtilityButton.css
  src/stories/Components/UtilityButton/UtilityButton.jsx
  src/stories/Components/UtilityButton/UtilityButton.stories.jsx
Labels: 기능 추가

#42 input form & modal
  src/stories/Components/GoFrontButton/GoFrontButton.css
  src/stories/Components/InputForm/InputForm.css
  src/stories/Components/InputForm/InputForm.jsx
  src/stories/Components/InputForm/InputForm.stories.jsx
  src/stories/Components/Modal/Modal.css
  src/stories/Components/Modal/Modal.jsx
  src/stories/Components/Modal/Modal.stories.jsx
Labels: 기능 추가

#47 버튼 active 추가
  src/stories/Components/UtilityButton/UtilityButton.css
Labels: 수정

#50 티켓 컴포넌트 생성
  package-lock.json
  package.json
  rollup.config.js
  src/index.js
  src/stories/Components/Ticket/GosrockLogoWhite.svg
  src/stories/Components/Ticket/Ticket.css
  src/stories/Components/Ticket/Ticket.jsx
  src/stories/Components/Ticket/Ticket.stories.jsx
  src/stories/Components/UtilityButton/UtilityButton.stories.jsx
Labels: 기능 추가

#55 qr코드 value값 인자로 변경, 빙글뱅글 애니메이션 추가
  src/stories/Components/Ticket/Ticket.css
  src/stories/Components/Ticket/Ticket.jsx
  src/stories/Components/Ticket/Ticket.stories.jsx
Labels: 기능 추가, 수정

#91 티켓 상태 및 티켓 리스트 컴포넌트
  package-lock.json
  package.json
  src/stories/Components/StateIcon/StateIcon.css
  src/stories/Components/StateIcon/StateIcon.jsx
  src/stories/Components/StateIcon/StateIcon.stories.jsx
  src/stories/Components/TicketList/GosrockLogo.svg
  src/stories/Components/TicketList/TicketList.css
  src/stories/Components/TicketList/TicketList.jsx
  src/stories/Components/TicketList/TicketList.stories.jsx
Labels: 기능 추가
